name: Glua Pretty-Print
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  lint-pretty-print:
    name: pretty-print
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download glualint
      run: |
        wget https://github.com/FPtje/GLuaFixer/releases/download/1.11.2/glualint-1.11.2-linux.zip
        unzip glualint-1.11.2-linux.zip
    - name: config
      run: mv glualint_prettyprint.json glualint.json
    - name: Lint
      run: |
        PATH=$PATH:$HOME/env/bin
        ./glualint .
