name: Glua

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: |
        pip install --user hererocks
        hererocks $HOME/env --luajit 2.0.3 --luarocks latest
        source $HOME/env/bin/activate
    - run: |
        luarocks show lanes > /dev/null || luarocks install lanes
        luarocks show luacheck > /dev/null || luarocks install luacheck
        luarocks list --outdated --porcelain | awk '{ print $1, $3 }' | xargs --no-run-if-empty -n 2 luarocks install
    - name: Download glualint
      run: |
        wget https://github.com/FPtje/GLuaFixer/releases/download/1.11.2/glualint-1.11.2-linux.zip
        unzip glualint-1.11.2-linux.zip
    - name: Lint
      run: |
        ./glualint . & true
        luacheck .
